# Generated by Django 4.2.2 on 2023-06-15 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("toDoListWebApp", "0002_task_created_at_alter_task_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="task",
            new_name="tasks",
        ),
        migrations.RenameField(
            model_name="tasks",
            old_name="task",
            new_name="taskDescription",
        ),
    ]
