# Generated by Django 4.2.2 on 2023-06-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toDoListWebApp", "0003_rename_task_tasks_rename_task_tasks_taskdescription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="user",
            new_name="userId",
        ),
    ]
