# Generated by Django 4.2 on 2023-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toDoListWebApp", "0004_rename_user_tasks_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="taskDescription",
            field=models.CharField(max_length=100, verbose_name="Task"),
        ),
    ]
